sudo: required

language: java

script: "mvn cobertura:cobertura"

services:
  - docker

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: echo "Unit Tests"
    - stage: integration tests
      jdk: oraclejdk11
      script: echo "Integration Tests"
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token