sudo: required

language: java

script:
  "mvn cobertura:cobertura"
  - echo "Deploying to GitHub Releases"
  # Package (build) the JAR
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
  before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "epicwin123"
    - git config --local user.email "facdis123@gmail.com"
    # Create temporary tag from date and Git log.
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
    # Set tag
    - git tag $TRAVIS_TAG
  deploy:
    provider: releases
    # This is the token we set before
    api_key: $GITHUB_OAUTH_TOKEN
    # Copy built JAR file to release.  JAR built in $TRAVIS_BUILD_DIR/target
    file: $TRAVIS_BUILD_DIR/target/seMethods.jar
    skip_cleanup: true

services:
  - docker

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token