sudo: required

language: java

script:
  "mvn cobertura:cobertura"

services:
  - docker

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token