sudo: required

language: java

script: "mvn cobertura:cobertura"

services:
  - docker

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: echo "Unit Tests"
    - stage: integration tests
      jdk: oraclejdk11
      script: echo "Integration Tests"
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script:
        - echo "Deploying to GitHub Releases"
        - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Kevin Chalmers"
        - git config --local user.email "k.chalmers@napier.ac.uk"
        # Create temporary tag from date and Git log.
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
        # Set tag
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        # Copy built JAR file.  JAR built in $TRAVIS_BUILD_DIR/
        file: $TRAVIS_BUILD_DIR/target/seMethods.jar
        skip_cleanup: true

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token