sudo: required

language: java

services:
  - docker

jobs:
  include:
  - stage: deploy
    install: skip
    jdk: oraclejdk11
    script:
    - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
    - docker-compose up --abort-on-container-exit

stages:
- name: deploy
  if: branch = master

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods
  - bash <(curl -s https://codecov.io/bash)